### ISSUE TITLE
Feature Request: Non-Installer release

### ISSUE THREAD

**Issue by mklaber** [brutaldev/StrongNameSigner#13]
I'd like to drop `StrongNameSigner.Console.exe` in a solution's *Shared* folder (where I keep powershell build and deployment scripts and whatnot) so that I don't have to install Strong Name Signer on every machine this will run on. I got it working by installing just the Console app and then copying the necessary DLLs from the install directory in to my *Shared* folder. It'd be great if there were a standalone exe or a ZIP of the program files so I don't actually have to install it.

Also, please add a time machine and go back and write this a year earlier when I was last mucking around with signed assemblies and sorely needed this. Thanks. :-)

**Comment by brutaldev** [comment]
Sure, a portable version won't be a problem. Furthermore, I should probably publish to NuGet as well as a tool so it's not a hard external dependency for build servers.

I'll take a look a this over the weekend. As for the time machine, not much I can do there but if someone else invents it one day I'll ask if I can borrow it quickly ;)

**Comment by mklaber** [comment]
:+1:

**Comment by brutaldev** [comment]
Uploaded to NuGet. You can install it as a dependency using `Install-Package Brutal.Dev.StrongNameSigner` or adding it to your `packages.config` like this:
```
<package id="Brutal.Dev.StrongNameSigner" version="1.4.4" />
```

Then access the portable files from `packages\Brutal.Dev.StrongNameSigner.1.4.4\tools\StrongNameSigner.Console.exe`.

You can also [download the package](<package id="Brutal.Dev.StrongNameSigner" version="1.4.4" />) directly and find the portable files in the `tools` directory since it's just a zip file anyway

Hope this helps.
